name: Deactivate Repos by Topic

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x" # Specify your Python version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests
          python -m pip install PyGithub
          python -m pip install urllib3

      - name: Run Python script
        env:
          JIT_CLIENT_ID: ${{ secrets.JIT_CLIENT_ID }}
          JIT_SECRET: ${{ secrets.JIT_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN provided by GitHub Actions by default
          GITHUB_ORGANIZATION: ${{ github.repository_owner }}
          TOPIC_TO_UNCOVER: <your topic name>
        run: python uncover_assets_by_topic.py
