{{- if .Values.client_id }}
{{- if .Values.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ecr-registry-helper-secrets
  namespace: {{ .Values.namespace }}
stringData:
  client_id: "{{ .Values.client_id }}"
  secret: "{{ .Values.secret }}"
{{- end }}
{{- end }}