name: 'Enforce Ticket'
on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  enforce-ticket:
    runs-on: ubuntu-latest
    steps:
      - name: Always succeed
        run: |
          echo "Skipping ticket enforcement - always succeeding"
          exit 0
