name: 'Enforce Ticket'
on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  enforce-ticket:
    uses: jitsecurity/centralized-workflows/.github/workflows/enforce-ticket.yml@main
